import { colorMix } from '../utils';

export const white = '#fff';
export const white2 = '#fafafa';
export const white3 = '#f5f5f5';
export const white4 = '#f2f2f2';
export const white5 = '#f0f0f0';
export const white6 = '#d9d9d9';

export const black = '#000';
export const black2 = '#141414';
export const black3 = '#1f1f1f';
export const black4 = '#2c2c2c';
export const black5 = '#333333';
export const black6 = '#404040';

//color palettes
export const bluebase = '#1890ff';
export const blue6 = bluebase;
export const blue1 = colorMix(blue6, 1);
export const blue2 = colorMix(blue6, 2);
export const blue3 = colorMix(blue6, 3);
export const blue4 = colorMix(blue6, 4);
export const blue5 = colorMix(blue6, 5);
export const blue7 = colorMix(blue6, 7);
export const blue8 = colorMix(blue6, 8);
export const blue9 = colorMix(blue6, 9);
export const blue10 = colorMix(blue6, 10);

export const purplebase = '#722ed1';
export const purple6 = purplebase;
export const purple1 = colorMix(purple6, 1);
export const purple2 = colorMix(purple6, 2);
export const purple3 = colorMix(purple6, 3);
export const purple4 = colorMix(purple6, 4);
export const purple5 = colorMix(purple6, 5);
export const purple7 = colorMix(purple6, 7);
export const purple8 = colorMix(purple6, 8);
export const purple9 = colorMix(purple6, 9);
export const purple10 = colorMix(purple6, 10);

export const cyanbase = '#13c2c2';
export const cyan6 = cyanbase;
export const cyan1 = colorMix(cyan6, 1);
export const cyan2 = colorMix(cyan6, 2);
export const cyan3 = colorMix(cyan6, 3);
export const cyan4 = colorMix(cyan6, 4);
export const cyan5 = colorMix(cyan6, 5);
export const cyan7 = colorMix(cyan6, 7);
export const cyan8 = colorMix(cyan6, 8);
export const cyan9 = colorMix(cyan6, 9);
export const cyan10 = colorMix(cyan6, 10);

export const greenbase = '#52c41a';
export const green6 = greenbase;
export const green1 = colorMix(green6, 1);
export const green2 = colorMix(green6, 2);
export const green3 = colorMix(green6, 3);
export const green4 = colorMix(green6, 4);
export const green5 = colorMix(green6, 5);
export const green7 = colorMix(green6, 7);
export const green8 = colorMix(green6, 8);
export const green9 = colorMix(green6, 9);
export const green10 = colorMix(green6, 10);

export const magentabase = '#eb2f96';
export const magenta6 = magentabase;
export const magenta1 = colorMix(magenta6, 1);
export const magenta2 = colorMix(magenta6, 2);
export const magenta3 = colorMix(magenta6, 3);
export const magenta4 = colorMix(magenta6, 4);
export const magenta5 = colorMix(magenta6, 5);
export const magenta7 = colorMix(magenta6, 7);
export const magenta8 = colorMix(magenta6, 8);
export const magenta9 = colorMix(magenta6, 9);
export const magenta10 = colorMix(magenta6, 10);

export const redbase = '#f5222d';
export const red6 = redbase;
export const red1 = colorMix(red6, 1);
export const red2 = colorMix(red6, 2);
export const red3 = colorMix(red6, 3);
export const red4 = colorMix(red6, 4);
export const red5 = colorMix(red6, 5);
export const red7 = colorMix(red6, 7);
export const red8 = colorMix(red6, 8);
export const red9 = colorMix(red6, 9);
export const red10 = colorMix(red6, 10);

export const orangebase = '#fa8c16';
export const orange6 = orangebase;
export const orange1 = colorMix(orange6, 1);
export const orange2 = colorMix(orange6, 2);
export const orange3 = colorMix(orange6, 3);
export const orange4 = colorMix(orange6, 4);
export const orange5 = colorMix(orange6, 5);
export const orange7 = colorMix(orange6, 7);
export const orange8 = colorMix(orange6, 8);
export const orange9 = colorMix(orange6, 9);
export const orange10 = colorMix(orange6, 10);

export const yellowbase = '#fadb14';
export const yellow6 = yellowbase;
export const yellow1 = colorMix(yellow6, 1);
export const yellow2 = colorMix(yellow6, 2);
export const yellow3 = colorMix(yellow6, 3);
export const yellow4 = colorMix(yellow6, 4);
export const yellow5 = colorMix(yellow6, 5);
export const yellow7 = colorMix(yellow6, 7);
export const yellow8 = colorMix(yellow6, 8);
export const yellow9 = colorMix(yellow6, 9);
export const yellow10 = colorMix(yellow6, 10);

export const volcanobase = '#fa541c';
export const volcano6 = volcanobase;
export const volcano1 = colorMix(volcano6, 1);
export const volcano2 = colorMix(volcano6, 2);
export const volcano3 = colorMix(volcano6, 3);
export const volcano4 = colorMix(volcano6, 4);
export const volcano5 = colorMix(volcano6, 5);
export const volcano7 = colorMix(volcano6, 7);
export const volcano8 = colorMix(volcano6, 8);
export const volcano9 = colorMix(volcano6, 9);
export const volcano10 = colorMix(volcano6, 10);

export const geekbluebase = '#2f54eb';
export const geekblue6 = geekbluebase;
export const geekblue1 = colorMix(geekblue6, 1);
export const geekblue2 = colorMix(geekblue6, 2);
export const geekblue3 = colorMix(geekblue6, 3);
export const geekblue4 = colorMix(geekblue6, 4);
export const geekblue5 = colorMix(geekblue6, 5);
export const geekblue7 = colorMix(geekblue6, 7);
export const geekblue8 = colorMix(geekblue6, 8);
export const geekblue9 = colorMix(geekblue6, 9);
export const geekblue10 = colorMix(geekblue6, 10);

export const limebase = '#a0d911';
export const lime6 = limebase;
export const lime1 = colorMix(lime6, 1);
export const lime2 = colorMix(lime6, 2);
export const lime3 = colorMix(lime6, 3);
export const lime4 = colorMix(lime6, 4);
export const lime5 = colorMix(lime6, 5);
export const lime7 = colorMix(lime6, 7);
export const lime8 = colorMix(lime6, 8);
export const lime9 = colorMix(lime6, 9);
export const lime10 = colorMix(lime6, 10);

export const goldbase = '#faad14';
export const gold6 = goldbase;
export const gold1 = colorMix(gold6, 1);
export const gold2 = colorMix(gold6, 2);
export const gold3 = colorMix(gold6, 3);
export const gold4 = colorMix(gold6, 4);
export const gold5 = colorMix(gold6, 5);
export const gold7 = colorMix(gold6, 7);
export const gold8 = colorMix(gold6, 8);
export const gold9 = colorMix(gold6, 9);
export const gold10 = colorMix(gold6, 10);

export const greybase = '#777';
export const grey6 = greybase;
export const grey1 = colorMix(grey6, 1);
export const grey2 = colorMix(grey6, 2);
export const grey3 = colorMix(grey6, 3);
export const grey4 = colorMix(grey6, 4);
export const grey5 = colorMix(grey6, 5);
export const grey7 = colorMix(grey6, 7);
export const grey8 = colorMix(grey6, 8);
export const grey9 = colorMix(grey6, 9);
export const grey10 = colorMix(grey6, 10);
